Repository TremboGuys/eatly_backend, pull requests merged in 2025-06, with the labels that each got.

#2 feat-1
  config/urls.py
  core/migrations/0004_address_alter_category_options_category_url_image.py
  core/models/category.py
  core/serializers/category.py
  core/views/category.py
  infra/__init__.py
  infra/cloudinary.py
  infra/helpers.py
  pdm.lock
  pyproject.toml
  uploader/__init__.py
  uploader/admin.py
  uploader/apps.py
  uploader/helpers/files.py
  uploader/migrations/0001_initial.py
  uploader/migrations/__init__.py
  uploader/models/__init__.py
  uploader/models/document.py
  uploader/models/image.py
  uploader/router.py
  uploader/serializers/__init__.py
  uploader/serializers/document.py
  uploader/serializers/image.py
  uploader/tests.py
  uploader/views.py
Labels: enhancement

#7 feat-3
  config/urls.py
  core/admin.py
  core/helpers.py
  core/migrations/0005_client.py
  core/migrations/0006_alter_client_cpf_alter_client_genre.py
  core/models/__init__.py
  core/models/client.py
  core/serializers/__init__.py
  core/serializers/client.py
  core/serializers/serializer_helpers.py
  core/views/__init__.py
  core/views/client.py
  core/views/view_helpers.py
  usuario/migrations/0002_usuario_role_register.py
  usuario/models.py
Labels: enhancement

#9 fix-8
  core/serializers/serializer_helpers.py
  core/views/client.py
  core/views/view_helpers.py
  usuario/managers.py
  usuario/migrations/0003_remove_usuario_role_register.py
  usuario/models.py
Labels: help wanted

#14 fix-12
  core/serializers/user.py
  usuario/managers.py
  usuario/migrations/0003_remove_usuario_role_register.py
Labels: bug

#16 package-15
  pdm.lock
  pyproject.toml
Labels: wontfix

#18 dev
  config/settings.py
  config/urls.py
  core/admin.py
  core/helpers.py
  core/migrations/0004_address_alter_category_options_category_url_image.py
  core/migrations/0005_client.py
  core/migrations/0006_alter_client_cpf_alter_client_genre.py
  core/migrations/0007_restaurant.py
  core/models/__init__.py
  core/models/category.py
  core/models/client.py
  core/models/restaurant.py
  core/serializers/__init__.py
  core/serializers/category.py
  core/serializers/client.py
  core/serializers/restaurant.py
  core/serializers/serializer_helpers.py
  core/serializers/user.py
  core/views/__init__.py
  core/views/category.py
  core/views/client.py
  core/views/restaurant.py
  core/views/view_helpers.py
  infra/__init__.py
  infra/cloudinary.py
  infra/helpers.py
  pdm.lock
  pyproject.toml
  uploader/__init__.py
  uploader/admin.py
  uploader/apps.py
  uploader/helpers/files.py
  uploader/migrations/0001_initial.py
  uploader/migrations/__init__.py
  uploader/models/__init__.py
  uploader/models/document.py
  uploader/models/image.py
  uploader/router.py
  uploader/serializers/__init__.py
  uploader/serializers/document.py
  uploader/serializers/image.py
  uploader/tests.py
  uploader/views.py
Labels: enhancement

#21 Dev
  config/settings.py
Labels: enhancement

#22 Add rest_framework in INSTALLED_APPS #19
  config/settings.py
  pdm.lock
  pyproject.toml
Labels: enhancement

#23 dev
  config/settings.py
  pdm.lock
  pyproject.toml
Labels: bug

#24 FEAT: Create build.sh #19.
  build.sh
Labels: enhancement
